name = "BoZos Animation"
filename = "BoZo.s.Animations.v1.0.0.zip"
side = "client"

[download]
url = "https://github.com/BoZo-Xo/BoZo-Player-Animations/releases/download/v1.0.0/BoZo.s.Animations.v1.0.0.zip"

hash-format = "sha256"
hash = "5a8fce4510950a2708a38d3b00d6d7899d7ab2205fe26de7ee83880e2834204e"